broadinstitute/orsp-pub

src/main/config/application.yml.ctmpl
Update the jdbc url to the minimum necessary for running liquibase. Added to both the dev and prod datasource urls
=> fix jdbc url for dev and prod

build.gradle, src/main/config/application.yml.ctmpl
Addresses the license incompatibility between ORSP and MySQL Connector
SourceClear issue here (for consent, but same for ORSP): https://broadinstitute-dsp.sourceclear.io/teams/jppForw/issues/licenses/5391952/3352887
=> Update to mariadb connector

docs/DEPLOY.md
The render configs and deploy tasks are broken under Gradle 5, so add some clarity around using `gradlew` instead of native `gradle` to run tasks.
=> Add Gradle 5 Info

grails-app/services/org/broadinstitute/orsp/QueryService.groovy
Fix queries that refer to old tables. This was missed in https://github.com/broadinstitute/orsp-pub/pull/19
=> Remove references to stale tables

grails-app/views/consentGroup/edit.gsp, grails-app/views/consentGroup/show.gsp
https://github.com/broadinstitute/orsp-pub/pull/new/BTRX-527
Show the collection id instead of the database id.
---
=> [BTRX-527][risk=no] Display Collection ID

docs/DEPLOY.md
No story. with the latest update to `vault`, the `auth` command is deprecated.
=> Auth command deprecated, use login instead

grails-app/controllers/org/broadinstitute/orsp/AuthenticatedController.groovy, grails-app/controllers/org/broadinstitute/orsp/ConsentGroupController.groovy, grails-app/controllers/org/broadinstitute/orsp/IrbController.groovy, grails-app/controllers/org/broadinstitute/orsp/NeController.groovy, grails-app/controllers/org/broadinstitute/orsp/NhsrController.groovy, grails-app/controllers/org/broadinstitute/orsp/SubmissionController.groovy, grails-app/domain/org/broadinstitute/orsp/Issue.groovy, grails-app/views/consentGroup/_attachConsentDocument.gsp, grails-app/views/consentGroup/list.gsp, grails-app/views/irb/show.gsp, grails-app/views/layouts/_footer.gsp, grails-app/views/ne/show.gsp, grails-app/views/nhsr/show.gsp, src/main/groovy/org/broadinstitute/orsp/SubmissionType.groovy
Partly addresses https://broadinstitute.atlassian.net/browse/BTRX-523
This PR targets `master` which is current production. `feature` has a very different document flow so I will address that aspect in a separate PR, these branches have diverged a lot in the interim. 
* Use one list of attachment types across all projects
* Update view of consent attachments inside of a project
* Don't restrict document uploads by type
* After uploading a consent group doc from inside of a project, redirect back to the consent group tab. It was redirecting to the documents tab.
* Order Amendments first under the submissions tab
* Upgrade [tinymce lib to v5](https://go.tiny.cloud/blog/tinymce-5-is-now-in-the-cloud/)
New consent document view from inside a project:
New view of adding a consent group …
=> [BTRX-523][risk=no] Use single list of attachment types across different projects

src/main/webapp/components/QuestionnaireWorkflow.js, src/main/webapp/project/NewProjectDetermination.js
Current State:
The button to proceed to the next question is a circle with an arrow. Users often instead look directly to the rectangular 'Next Step' button below and click it to proceed, thinking they are doing so correctly but are confused when they cannot proceed.
Future State: 
Change the circular arrow button to say "Next Question" and choose the most appropriate button style/shape. Please also update the red help text which appears when the 'Next Step' button is clicked prior to 100% of answers being provided to say "Please answer the next question(s) above before moving to the next step"
Options
---
=> BTRX-593 ORSP - New Project Generation Workflow Button Updates

grails-app/controllers/org/broadinstitute/orsp/AuthenticatedController.groovy, grails-app/controllers/org/broadinstitute/orsp/ConsentGroupController.groovy, grails-app/controllers/org/broadinstitute/orsp/IrbController.groovy, grails-app/controllers/org/broadinstitute/orsp/NeController.groovy, grails-app/controllers/org/broadinstitute/orsp/NhsrController.groovy, grails-app/controllers/org/broadinstitute/orsp/SubmissionController.groovy, grails-app/domain/org/broadinstitute/orsp/Issue.groovy, grails-app/services/org/broadinstitute/orsp/IssueService.groovy, grails-app/views/consentGroup/_attachConsentDocument.gsp, grails-app/views/consentGroup/list.gsp, grails-app/views/irb/show.gsp, grails-app/views/layouts/_footer.gsp, grails-app/views/ne/show.gsp, grails-app/views/nhsr/show.gsp, src/main/groovy/org/broadinstitute/orsp/SubmissionType.groovy
Addresses https://broadinstitute.atlassian.net/browse/BTRX-523
Copy of https://github.com/broadinstitute/orsp-pub/pull/57 against the `feature` branch
See https://github.com/broadinstitute/orsp-pub/pull/57
---
=> [BTRX-523][risk=no] Use single list of attachment types across different projects (#57)

grails-app/views/dataUseLetter/index.gsp, grails-app/views/layouts/main_component.gsp, grails-app/views/newConsentGroup/index.gsp, grails-app/views/newProject/index.gsp, grails-app/views/search/index.gsp
* Make all of the primary react-based `index.gsp` files use the same template. 
* Pull all constants into the same object(s) so they can be reused.
View search, project, consent group pages - should be no errors
There is a lot we can do to refactor further, but I leave that for other PRs. This PR is meant to start us in the right direction in terms of consolidating react behavior. The more we can pull out of individual gsps, the easier it will be to consolidate them later on as well as convert other features more easily.
Also - this does not address the templates we are using (`_index.gsp` files). We need to figure that out too. 
---
=> Refactor the react index.gsp files

grails-app/views/layouts/main_component.gsp, src/main/webapp/components/footer.js, webpack.config.js
See https://broadinstitute.atlassian.net/browse/BTRX-623
* Add a footer component
* Load footer in the react template
* Add todos for removing outdated code once the conversion is complete.
* Changes to `main_component.gsp` are mainly copying the existing footer code so it can be in one place for later one when we remove all non-react dependencies. 
* Alphabetized files in `webpack.config.js`
View both a react page (i.e. search) and a non-react page (i.e. about). Both should have the same footer and footer link behavior
---
=> [BTRX-623][risk=no] Convert footer to react

grails-app/views/notify/generalInfo.gsp, src/main/webapp/components/Fundings.js, src/main/webapp/components/InternationalCohorts.js, src/main/webapp/components/RequestClarificationDialog.js, src/main/webapp/components/Security.js, src/main/webapp/components/SecurityReview.js, src/main/webapp/components/Wizard.js, src/main/webapp/consentGroup/NewConsentGroup.js, src/main/webapp/consentGroupReview/ConsentGroupReview.js, src/main/webapp/index.css, src/main/webapp/project/NewProject.js, src/main/webapp/project/NewProjectDetermination.js, src/main/webapp/projectReview/ProjectReview.js
Page/s: Consent Group creation and review
Update the first International Cohorts question to include the link: “Are samples or individual-level data sourced from a country in the European Economic Area? https://www.imf.org/external/pubs/ft/fandd/2014/03/europeaneconomicarea.htm”
Page: Project/Consent Group creation
Add the following text below the main page title on both Project and Consent Group creation workflows: “Note that this application cannot be saved and returned to for completion later. However, allowing the page to remain open in your browser will permit you to return to the application at any time.”
Pages: Project review > Request Clarification dialog
Change text on Clarifications popup box button to say ‘Request Clarification’ instead of ‘Submit Clarification’
Page/s: Project …
=> BTRX-627 ORSP - Several text changes

grails-app/controllers/org/broadinstitute/orsp/UrlMappings.groovy, grails-app/controllers/org/broadinstitute/orsp/api/ProjectController.groovy, grails-app/services/org/broadinstitute/orsp/IssueService.groovy, package.json, src/main/webapp/consentGroup/NewConsentGroup.js, src/main/webapp/project/NewProject.js, src/main/webapp/projectReview/ProjectReview.js, src/main/webapp/util/ajax.js
[BTRX-602](https://broadinstitute.atlassian.net/browse/BTRX-602): ORSP - Project Info tab: Put the new 'Add New Consent Group' button next to the 'Edit' button
[BTRX-591](https://broadinstitute.atlassian.net/browse/BTRX-591): ORSP - Technical debt - Create API to get project type
- Code related to mapping `consentUpload` new variable (creation and update)
- Created a new backend api that returns a project type, given a projectKey. This was a technical debt.
##
**Note (Just as a discussion starter):**
It would be really interesting to correct webpack.config in order to enable the use of async/await functionallity in our code. This would make promises handling easier and shorten our code. 
Apparently the problem is that `regeneratorRuntime` is undefined, this is due to  having a custom …
=> BTRX - 602 & 591  - Put 'Add New Consent Group' button in Project review - Project type Api

src/main/webapp/components/AddDocumentDialog.js
Every time the user clicks _Get sherable link_ a new token is generated and then copied to the OS clipboard. https://broadinstitute.atlassian.net/browse/BTRX-583
Added a new function of _navigator_ API of the browser. To see more about the support across platforms this is a good reference https://caniuse.com/#search=clipboard
---
=> [BTRX-583] Copy DUL link to clipboard

src/main/webapp/components/Fundings.js, src/main/webapp/project/NewProject.js, src/main/webapp/project/NewProjectGeneralData.js, src/main/webapp/projectReview/ProjectReview.js
[BTRX-631](https://broadinstitute.atlassian.net/browse/BTRX-631): ORSP - Make award number required on federal primer funding.
- Added extra validation for Fundings.
- Modify Ui to display required warning.
- Try to submit a new project or an edit suggestion in review project having a `Federeal Prime`  funding and leaving its Award Number empty. It should validate this last field as required. 
- Award number is not required for the remaining 'fundings'.
---
=> BTRX - 631 - Make federal prime award number required in Fundings

grails-app/views/consentGroup/list.gsp, src/main/webapp/components/RequestClarificationDialog.js, src/main/webapp/consentGroup/NewConsentGroup.js, src/main/webapp/consentGroupReview/ConsentGroupReview.js, src/main/webapp/project/NewProject.js, src/main/webapp/projectReview/ProjectReview.js
[BTRX-628](https://broadinstitute.atlassian.net/browse/BTRX-628): ORSP - Add feddback message after project/CG submission
- Modify pre-existent temporizer method to accept as paramether time, message, and alert type to be re-used.
**Note:** The same functionality was added in gsp code, this should be temporal until "consent group" tab is migrated to react.
- Create a new Project, after submission, a green alert message should be displayed at the top indicating the submission has been successfully made. This message should disapear after 8 seconds.
- The same behaviour as above should happen after a new consent group is created, but the message is displayed in Project's Consent Group tab. This message should disapear after 8 seconds.
---
=> BTRX - 628 - Feedback after submission Project & CG 

src/main/webapp/dataUseLetter/DataUseLetter.js
https://broadinstitute.atlassian.net/browse/BTRX-679
If user selects GSR=true a text input appears. We need to change the label of that Text Box from "Please Specify" to "Please explain why the GSR should be designated as sensitive."
---
=> BTRX-679-eDUL Text

grails-app/services/org/broadinstitute/orsp/QueryService.groovy
Hotfix for [PR-160](https://github.com/broadinstitute/orsp-pub/pull/160)
[BTRX-682](https://broadinstitute.atlassian.net/browse/BTRX-682)
- When `findCollectionLinksByConsentKeyAndProjectKey()` gets each collectionLink's documents, and there are at least one without documents, it sets its collectionLink document as Null, which causes conflicts in the Ui. To fix this we used getOrDefault.
- Associate a Sample Collection without any document uploaded to a Sample / Data cohort. Access to its linkInfo page and select that Sample Collection "Documents" tab.
---
=> BTRX - 682 - Hotfix

grails-app/views/consentGroup/show.gsp
[BTRX-677](https://broadinstitute.atlassian.net/browse/BTRX-677) : Review / Refactor Sample/Data Cohort approval process
- Remove deprecated status from sample/data cohorts.
- The header status "New Status" should not be visible anymore in Sample / Data cohorts.
---
=> BTRX - 677 - Remove data cohorts status

grails-app/views/layouts/main_component.gsp, src/main/webapp/components/InputFieldSelect.js, src/main/webapp/linkWizard/LinkQuestions.js, src/main/webapp/linkWizard/LinkWizard.js, src/main/webapp/linkWizard/SelectSampleConsent.js, src/main/webapp/linkWizard/index.js, src/main/webapp/util/ajax.js
https://broadinstitute.atlassian.net/browse/BTRX-685
The Sample Collection select component now show a heading for the already linked SC, and another heading for the non linked SC.
Describe for the reviewer how to test the specifics of this PR, both positive and negative cases. Also both selects now displays a loading indicator.
---
=> [BTRX-685] Select sample already associated

src/main/webapp/adminOnly/AdminOnly.js, src/main/webapp/projectReview/ProjectReview.js
- https://broadinstitute.atlassian.net/browse/BTRX-699
- https://broadinstitute.atlassian.net/browse/BTRX-704
- In "Notes to ORSP" add a radio button with a new option.
- In Admin Only Tab, change Traking Number to "Protocol Number".
---
=> Add Option to "Notes to ORSP" and Change Text in Admin Only Tab

src/main/webapp/components/Table.js, src/main/webapp/consentGroupReview/ConsentGroupReview.js
https://broadinstitute.atlassian.net/browse/BTRX-705
- Link names and urls are fully displayed when you mouseover in a link (tooltip/title)
- Column width size is improved depending on the column content, assigning more width to columns with larger strings
- Sample Collection Table
- Project > Documents Tab 
- Consent Group
---
=> Btrx 705 improve sample collection

grails-app/views/base/_topNav.gsp, src/main/webapp/project/NewProject.js, src/main/webapp/project/NewProjectGeneralData.js, src/main/webapp/projectReview/ProjectReview.js
- https://broadinstitute.atlassian.net/browse/BTRX-708
- https://broadinstitute.atlassian.net/browse/BTRX-709
- Delete all options but "New Project" in the "Admin" Top Nav.
- Delete "Subject Protection" question from New Project flow and Review Project.
- As an Admin user, the "Admin" drop down in the Header should only show "New Project" option.
- When creating or reviewing a Project, "Subject Protection" related question should not appear any more.
---
=> Remove Top Nav Options and Project Question

grails-app/taglib/org/broadinstitute/orsp/AuthTagLib.groovy, grails-app/views/base/_topNav.gsp, grails-app/views/layouts/main_component.gsp, src/main/webapp/components/Documents.js, src/main/webapp/components/RoleManagementEdit.js, src/main/webapp/consentGroupReview/ConsentGroupReview.js, src/main/webapp/projectReview/ProjectReview.js, src/main/webapp/util/roles.js
There's no story for this fix
- Change roles that are able to see Admin drop down from top nav, to be consistent to rest of the app.
- Change isAdmin and isViewer global variables to be Boolean instead of strings.
- Fix Compliance Office to default check Admin, in Roles Management
- Check that a read only user cannot perform any admin action across the app.
- Verify that read only users cannot see Admin dropdown in the top navigation options
- Users with Compliance Office role, will be seen as Admins in Roles management table. Also as a default checked option in its edition.
---
=> Feature - Hotfix 

grails-app/services/org/broadinstitute/orsp/IssueService.groovy
No story
- Removed old delete Consent Collection Link logic from Issue update. This is being handled elsewhere
---
=> Remove ccl delete logic

grails-app/views/index/about.gsp
[BTRX-442](https://broadinstitute.atlassian.net/browse/BTRX-442) : ORSP: Create a user guide for the new system
- Change user's guide text in "About" page.
- Access to About page from top navigation bar link. The new user guide text should be there.
---
=> BTRX - 442 - Create a user guide for the new system

grails-app/controllers/org/broadinstitute/orsp/ConsentGroupController.groovy, grails-app/views/consentGroup/show.gsp
The UI logic around when to show the create data use restriction page was incorrectly looking at only one kind of document type. This PR moves that logic to the controller and looks at any of the kinds of du letters that are now valid.
=> [No Jira] Move du letter logic to the controller

grails-app/controllers/org/broadinstitute/orsp/SearchController.groovy, grails-app/services/org/broadinstitute/orsp/PermissionService.groovy, grails-app/services/org/broadinstitute/orsp/QueryService.groovy, src/main/groovy/org/broadinstitute/orsp/IssueSearchItemDTO.groovy, src/main/webapp/search/Search.js
This is a fix the the issue (Err 502) verified on Cloud deployment + Ingress Load Balancer. It is an alternative query to NOT use hibernate addEntity in order to avoid overhead that seems to be causing 502 errors.
The search query was replaced with a new one, not using AddEntity and therefore using manaul mapping of returned values. Additionally, user names search was included to avoid extra sql requests. 
---
=> Search Refactor to fix 502 Error on Cloud

build.gradle
https://broadinstitute-dsp.sourceclear.io/workspaces/jppForw/issues/vulnerabilities/7039290/18759627
https://broadinstitute-dsp.sourceclear.io/workspaces/jppForw/issues/vulnerabilities/7039290/18759626
```
This vulnerability is in a direct dependency. Vulnerable library jackson-databind was found in build.gradle It can be fixed by updating the version of the library in your project and rebuilding it.
```
=> [risk=no] Jackson security update
