- hooks/README.md
- hooks/apply-git-secrets.sh
- hooks/commit-msg
- hooks/pre-commit
- hooks/prepare-commit-msg
> Adding git secrets hooks

- README.md
> point circle badge to master

- build.gradle
Addresses: 
* https://broadinstitute-dsp.sourceclear.io/teams/jppForw/issues/libraries/5392009/11143795
* https://broadinstitute-dsp.sourceclear.io/teams/jppForw/issues/libraries/5392009/11143802
* https://broadinstitute-dsp.sourceclear.io/teams/jppForw/issues/libraries/5392009/11143803
* https://broadinstitute-dsp.sourceclear.io/teams/jppForw/issues/libraries/5392009/11143799
> SourceClear: various lib updates

- grails-app/views/ne/_details.gsp
- grails-app/views/ne/create.gsp
- grails-app/views/ne/edit.gsp
- grails-app/views/nhsr/_details.gsp
- grails-app/views/nhsr/create.gsp
- grails-app/views/nhsr/edit.gsp
https://broadinstitute.atlassian.net/browse/BTRX-469
Minor language updates
Deployed to [dev](https://orsp.broadinstitute.org/dev/) for manual review.
> [BTRX-469] Update "biospecimen" Language

- src/main/webapp/components/Fundings.js
- src/main/webapp/components/InputField.css
- src/main/webapp/components/InputField.js
- src/main/webapp/components/InputFieldDatePicker.js
- src/main/webapp/components/InputFieldRadio.js
- src/main/webapp/components/InputFieldSelect.js
- src/main/webapp/components/InputFieldText.js
- src/main/webapp/components/InputFieldTextArea.js
- src/main/webapp/components/InputYesNo.css
- src/main/webapp/components/InputYesNo.js
- src/main/webapp/components/InstitutionalSource.js
- src/main/webapp/components/MultiSelect.js
- src/main/webapp/index.css
Jira story [BTRX-518](https://broadinstitute.atlassian.net/browse/BTRX-518)
---
> [Btrx-518] Input fields read only 

- src/main/webapp/consentGroup/NewConsentGroup.js
- src/main/webapp/consentGroup/NewConsentGroupGeneralData.js
https://broadinstitute.atlassian.net/browse/BTRX-492
> Update MTA Question

- grails-app/assets/javascripts/projectReview.js
- src/main/webapp/projectReview/ProjectReview.js
> HotFix - Typo fix

- src/main/webapp/components/MultiSelect.js
Fixed multiselect edit mode component.
[Jira story](https://broadinstitute.atlassian.net/browse/BTRX-532)
---
> [BTRX-532] Fixed multiselect

- grails-app/controllers/org/broadinstitute/orsp/api/NewConsentGroupController.groovy
- grails-app/controllers/org/broadinstitute/orsp/api/ProjectController.groovy
- grails-app/services/org/broadinstitute/orsp/IssueService.groovy
- grails-app/utils/org/broadinstitute/orsp/utils/IssueUtils.groovy
> Update issue - Refactor existing code to be used on new flow

- src/main/webapp/components/InputFieldDatePicker.js
- src/main/webapp/components/InputFieldSelect.js
- src/main/webapp/components/MultiSelect.js
- src/main/webapp/consentGroup/NewConsentGroupGeneralData.js
- src/main/webapp/consentGroupReview/ConsentGroupReview.js
- src/main/webapp/projectReview/ProjectReview.js
In order to edit fields in Review Consent Group tab first should be working properly all the components. This PR fixes a various bugs that are in _New Consent Group_ form and _Review_ tab.
[https://broadinstitute.atlassian.net/browse/BTRX-532](https://broadinstitute.atlassian.net/browse/BTRX-532)
---
> [BTRX-535] consent group creation and review fixes

- grails-app/domain/org/broadinstitute/orsp/Issue.groovy
- grails-app/views/consentGroup/show.gsp
- grails-app/views/irb/show.gsp
- grails-app/views/ne/show.gsp
- grails-app/views/nhsr/show.gsp
> BTRX-530 Add New Status to Header

- src/main/webapp/project/NewProjectGeneralData.js
- src/main/webapp/projectReview/ProjectReview.js
> Submit Edit - Add validations

- grails-app/domain/org/broadinstitute/orsp/Issue.groovy
- grails-app/domain/org/broadinstitute/orsp/IssueExtraProperty.groovy
- grails-app/services/org/broadinstitute/orsp/IssueService.groovy
- src/main/webapp/project/NewProject.js
- src/main/webapp/projectReview/ProjectReview.js
> Project Bug Fixing

- src/main/webapp/components/InputField.css
- src/main/webapp/components/InputFieldTextArea.js
- src/main/webapp/projectReview/ProjectReview.js
> Show hide buttons & other Minor Fixes

- grails-app/domain/org/broadinstitute/orsp/StorageDocument.groovy
- grails-app/migrations/changelog-master.xml
- grails-app/migrations/changesets/changelog-7.0.xml
- grails-app/services/org/broadinstitute/orsp/QueryService.groovy
- grails-app/services/org/broadinstitute/orsp/StorageProviderService.groovy
- src/main/webapp/components/MultiSelect.js
> BTRX-547 Refactor document storage service to include document version.

- src/main/webapp/components/AddDocumentDialog.js
- src/main/webapp/components/InputFieldText.js
> BTRX-545 Implement Data Use Letter special case

- grails-app/controllers/org/broadinstitute/orsp/UrlMappings.groovy
- grails-app/controllers/org/broadinstitute/orsp/api/FileHelperController.groovy
- grails-app/services/org/broadinstitute/orsp/QueryService.groovy
- grails-app/services/org/broadinstitute/orsp/StorageProviderService.groovy
Updates the document version relative to its file type, date and project. 
It uses an end-point `[server-url]/api/files-helper/update` method PUT . It should be executed one time. If it's executed a second time it will take no effect.
---
> [BTRX-553] Update legacy document version 

- src/main/webapp/components/InputField.css
- src/main/webapp/components/InputFieldCheckbox.js
- src/main/webapp/components/InputFieldSelect.js
- src/main/webapp/components/MultiSelect.js
- src/main/webapp/consentGroup/NewConsentGroupGeneralData.js
- src/main/webapp/consentGroupReview/ConsentGroupReview.js
- src/main/webapp/dataUseLetter/DataUseLetter.js
- src/main/webapp/index.css
https://broadinstitute.atlassian.net/browse/BTRX-571
---
> Select Inputs Read Only Fix

- package.json
- src/main/webapp/consentGroupReview/ConsentGroupReview.js
https://broadinstitute.atlassian.net/browse/BTRX-573
---
> Consent Group Improvements

- grails-app/controllers/org/broadinstitute/orsp/api/DulNotifyController.groovy
- grails-app/views/notify/dulFormLink.gsp
Add text template the url to DUL form. 
---
> Add link to email DUL Form

- build.gradle
[BTRX-563](https://broadinstitute.atlassian.net/browse/BTRX-563)
Update jackson databind version
---
> BTRX - 563 - Upgrade jackson databind

- grails-app/domain/org/broadinstitute/orsp/Issue.groovy
> [risk=no] Refactor Issue.getExtraPropertiesMap

- grails-app/domain/org/broadinstitute/orsp/Issue.groovy
No ticket
Minor refactoring
---
> [risk=no] Another Refactor

- src/main/webapp/projectReview/ProjectReview.js
> BTRX-596 ORSP - Project Edits Workflow Move 'Notes to ORSP' to top

- grails-app/views/consentGroup/show.gsp
- grails-app/views/irb/show.gsp
- grails-app/views/ne/show.gsp
- grails-app/views/nhsr/show.gsp
Addresses:
https://broadinstitute.atlassian.net/browse/BTRX-603
- The title of the 'Comments' tab should be erased and changed to 'Messages' for Projects and Consent Groups.
- The tabs in Projects should appear in the following order from left to right: Project Info, Documents, Consent Groups, Submissions, Messages, History, Workspace.
- Entering a Project, you will land on the Project Info page.
- Order in Consent Group: Review, Details, Docs New, Docs, Messages, History.
> Btrx 603 change comments to messages

- grails-app/views/layouts/main_component.gsp
- src/main/webapp/dataUseLetter/index.js
Make the data use component similar to other components in terms of its grails dependencies. 
---
> Minor refactoring of data use component

- grails-app/domain/org/broadinstitute/orsp/Issue.groovy
- grails-app/domain/org/broadinstitute/orsp/IssueExtraProperty.groovy
- grails-app/services/org/broadinstitute/orsp/IssueService.groovy
- src/main/groovy/org/broadinstitute/orsp/ProjectExtraProperties.groovy
- src/main/webapp/components/InputFieldSelect.js
- src/main/webapp/project/NewProject.js
- src/main/webapp/project/NewProjectGeneralData.js
- src/main/webapp/projectReview/ProjectReview.js
- src/main/webapp/util/TypeDescription.js
[BTRX-630](https://broadinstitute.atlassian.net/browse/BTRX-630): Change IRB question in project creation and review
- This value didn't exist in the current new project workflow, so this code includes the adding this value to the ui and its mapping in the backend.
- In this previous PR, a validation requirement was added for reviewing legacy projects. This fix added a bug for the rest of the projects, which is fixed here.
- When creating a new project, you should be able to see this new select option for Irb Referral. It is not a required value.
- In review this should be visible as read-only, and should display differences if this value is edited in its correspondent edit mode.
---
> BTRX - 630 - Change IRB question in project creation and review

- grails-app/domain/org/broadinstitute/orsp/Issue.groovy
No Jira
Eagerly fetch extra properties and fundings to cut down the number of single select queries. 
---
> Eager fetch some associations

- src/main/webapp/project/NewProject.js
- src/main/webapp/project/NewProjectDocuments.js
- src/main/webapp/project/NewProjectGeneralData.js
- src/main/webapp/projectReview/ProjectReview.js
Addresses:
Move the Attestation question from General Data Tab to last Step before Submit.
https://broadinstitute.atlassian.net/browse/BTRX-665
---
> BTRX-665-Move Attestation question

- grails-app/domain/org/broadinstitute/orsp/Issue.groovy
- grails-app/domain/org/broadinstitute/orsp/IssueExtraProperty.groovy
- grails-app/services/org/broadinstitute/orsp/IssueService.groovy
- src/main/groovy/org/broadinstitute/orsp/ProjectExtraProperties.groovy
- src/main/webapp/adminOnly/AdminOnly.js
- src/main/webapp/components/Fundings.js
- src/main/webapp/components/InputField.css
- src/main/webapp/components/InputTextList.js
- src/main/webapp/components/InstitutionalSource.js
https://broadinstitute.atlassian.net/browse/BTRX-651
See "Expiration Date" on the current new IRB page. We'd like to see that be one of the fields on the admin tab.
---
> BTRX-651-Add IRB Expiration date to Admin Tab

- src/main/webapp/adminOnly/AdminOnly.js
- src/main/webapp/util/TypeDescription.js
https://broadinstitute.atlassian.net/browse/BTRX-669
Admin Tab: Please add the Drop-down feature under "Type of Initial Review" (current functionality in production under Review Category) Expedited, Exempt, Full Board, Not Human Subjects Research, Not Engaged* (*new choice).
---
> BTRX-669-Change Field in Admin Tab

- build.gradle
- grails-app/services/org/broadinstitute/orsp/ConsentService.groovy
- src/test/groovy/org/broadinstitute/orsp/ConsentServiceUnitSpec.groovy
No Jira. Seeing auth problems on prod ORSP that we cannot reproduce locally.
Added some logging.Also upgraded jackson since that's been a sore spot for security for some time now.
> Add Consent Logging

- grails-app/controllers/org/broadinstitute/orsp/api/NewConsentGroupController.groovy
- grails-app/controllers/org/broadinstitute/orsp/api/ProjectController.groovy
- grails-app/views/consentGroup/list.gsp
- src/main/webapp/project/NewProject.js
- src/main/webapp/project/NewProjectDocuments.js
- src/main/webapp/project/NewProjectGeneralData.js
- src/main/webapp/projectReview/ProjectReview.js
- src/main/webapp/util/ajax.js
https://broadinstitute.atlassian.net/browse/BTRX-671
Refactored new Project and Review Project.
---
> [BTRX-671] Refactor Project

- grails-app/services/org/broadinstitute/orsp/QueryService.groovy
No Jira
Fix bug where we were filtering on the wrong document id.
---
> [risk=no] Fix doc filter bug

- .github/PULL_REQUEST_TEMPLATE.md
No Jira
Update the pr template with some more explanatory text.
Add Belatrix as a reviewer
None necessary
---
> [risk=no] Add to PR template

- grails-app/views/consentGroup/list.gsp
- grails-app/views/irb/show.gsp
- grails-app/views/ne/show.gsp
- grails-app/views/nhsr/show.gsp
https://broadinstitute.atlassian.net/browse/BTRX-672
- Rename Consent Group tab as Sample/Data Cohort
- Refactor buttons in the tab to be : Add New Sample/Data Cohort
- Change all Consent Group in that tab to Sample/Data Cohort
-
---
> BTRX-672-Refactor Consent Group Tab

- .github/PULL_REQUEST_TEMPLATE.md
- src/main/webapp/components/AddDocumentDialog.js
- src/main/webapp/consentGroup/NewConsentGroup.js
- src/main/webapp/consentGroup/NewConsentGroupDocuments.js
- src/main/webapp/consentGroupDocuments/ConsentGroupDocuments.js
- src/main/webapp/consentGroupReview/ConsentGroupReview.js
- src/main/webapp/project/NewProject.js
- src/main/webapp/project/NewProjectDocuments.js
- src/main/webapp/projectDocument/ProjectDocument.js
- src/main/webapp/util/DocumentType.js
https://broadinstitute.atlassian.net/browse/BTRX-681
Added descriptive text in documents tabs. New lists of documents for Projects and CG.
---
> [BTRX-681] Refactor Documents Types

- src/main/webapp/linkWizard/LinkWizard.js
- src/main/webapp/linkWizard/SelectSampleConsent.js
https://broadinstitute.atlassian.net/browse/BTRX-688
Now the documents list type is the same as new Sample/Data Cohort. And minor style correction.
---
> [BTRX-688] Document Types in Add Sample

- src/main/webapp/components/Wizard.js
- src/main/webapp/util/Utils.js
https://broadinstitute.atlassian.net/browse/BTRX-691
The only change needed was to add line in the Wizard Step component.
---
> [BTRX-691] Scroll top wizards

- package.json
Addresses github security alert: https://nvd.nist.gov/vuln/detail/CVE-2019-10742
Update axios library
---
> [risk=no] Update Axios

- grails-app/controllers/org/broadinstitute/orsp/ReadOnlyInterceptor.groovy
- src/main/webapp/components/Wizard.js
https://broadinstitute.atlassian.net/browse/BTRX-689
Filters access to functionalities when the user is Read Only Admin.
---
> [BTRX-689] Enforce backend roles

- src/main/webapp/projectContainer/ProjectContainer.js
- src/main/webapp/projectReview/ProjectReview.js
- Minor code refactor
- Update history tab on content changes
---
> BTRX - Add history update

- grails-app/services/org/broadinstitute/orsp/IssueService.groovy
Fix Approved status change.
Include a high level summary of the changes and what they are intended for.
---
> Fix approved project status

- grails-app/views/consentGroup/list.gsp
https://broadinstitute.atlassian.net/browse/BTRX-724
Changed text from _Consent Group_ to _Sample Data/Cohort_.
---
> [BTRX-724] Change alert text

- src/main/webapp/consentGroupReview/ConsentGroupReview.js
- src/main/webapp/projectReview/ProjectReview.js
Minor change to fix the sub status of review Project and CG review.
Include a high level summary of the changes and what they are intended for.
---
> Fix sub status

- src/main/webapp/components/Documents.js
No ticket
Added isRender property to DUL panel to make it visible only in CG Documents
DUL Panel should not appear in Project Documents page
---
> Only Render DUL Panel in CG

- package.json
high vulnerability reported by GitHb
upgrading lodash to fix vulnerability, as suggested by GitHub.
---
> upgrading lodash to fix vulnerability

- grails-app/controllers/org/broadinstitute/orsp/api/ReportController.groovy
- grails-app/services/org/broadinstitute/orsp/QueryService.groovy
- src/main/webapp/components/Comments.js
- src/main/webapp/components/TableComponent.js
- src/main/webapp/fundingSourceReport/FundingsSourceReport.js
- src/main/webapp/reviewCategories/ReviewCategories.js
- src/main/webapp/util/ReportConstants.js
- src/main/webapp/util/ajax.js
https://broadinstitute.atlassian.net/browse/BTRX-614
Add pagination to review category report. 
Go to Admin Menu => Review Category Report
---
> Convert Review Category Report - Pagination
